/**
 * GENERATED by backend/src/db/generateSchemaTypes.ts from the database that
 * db/init/01-schema.sql builds. Do not edit: run `npm run db:types` after a
 * schema change, and `npm run db:types:check` (a check-tier gate, ADR-0064)
 * fails when this file and the schema disagree.
 *
 * Every interface is a relation's *select shape*: what `pg` returns for
 * `SELECT column` with no type parser installed. `int8` and `numeric` arrive
 * as strings, timestamps as `Date`, a geometry as hex EWKB, JSON as `unknown`.
 * A view's columns are all nullable, since the catalog records no NOT NULL for
 * them.
 */

/** Postgres enum `auth_provider`. */
export type AuthProvider = "local" | "google" | "apple";

/** Postgres enum `user_role`. */
export type UserRole = "user" | "curator" | "admin";

/** The table `administrative_divisions`. */
export interface AdministrativeDivisionsRow {
  id: number;
  name: string;
  parent_id: number | null;
  has_children: boolean;
  gadm_uid: number | null;
  geom: string | null;
  geom_simplified_low: string | null;
  geom_simplified_medium: string | null;
  anchor_point: string | null;
  focus_bbox: number[] | null;
  geom_area_km2: number | null;
  name_normalized: string | null;
  created_at: Date | null;
  updated_at: Date | null;
  geom_3857: string | null;
  geom_simplified_low_3857: string | null;
  geom_overview_3857: string | null;
  geom_simplified_coarse_3857: string | null;
  geom_simplified_medium_3857: string | null;
}

/** The table `ai_learned_rules`. */
export interface AiLearnedRulesRow {
  id: number;
  feature: string;
  rule_text: string;
  context: string | null;
  created_at: Date | null;
}

/** The table `ai_settings`. */
export interface AiSettingsRow {
  key: string;
  value: string;
  updated_at: Date | null;
}

/** The table `ai_usage_log`. */
export interface AiUsageLogRow {
  id: number;
  feature: string;
  model: string;
  description: string | null;
  api_calls: number | null;
  prompt_tokens: number | null;
  completion_tokens: number | null;
  total_cost: string | null;
  duration_ms: number | null;
  created_at: Date | null;
}

/** The table `curator_assignments`. */
export interface CuratorAssignmentsRow {
  id: number;
  user_id: number;
  scope_type: string;
  region_id: number | null;
  source_id: number | null;
  assigned_by: number;
  assigned_at: Date | null;
  notes: string | null;
}

/** The table `curator_queue_set_aside`. */
export interface CuratorQueueSetAsideRow {
  user_id: number;
  sync_log_id: number;
  created_at: Date;
}

/** The table `data_assertion_acceptances`. */
export interface DataAssertionAcceptancesRow {
  id: number;
  assertion_id: string;
  accepted_count: number;
  accepted_by: number;
  accepted_at: Date;
}

/** The table `email_verification_tokens`. */
export interface EmailVerificationTokensRow {
  id: number;
  user_id: number;
  token_hash: string;
  expires_at: Date;
  created_at: Date | null;
}

/** The table `experience_conflict_decisions`. */
export interface ExperienceConflictDecisionsRow {
  id: string;
  experience_id: number;
  field: string;
  declined: unknown;
  decided_by: number | null;
  decided_at: Date;
}

/** The table `experience_curation_log`. */
export interface ExperienceCurationLogRow {
  id: number;
  experience_id: number;
  curator_id: number;
  action: string;
  region_id: number | null;
  details: unknown | null;
  created_at: Date | null;
}

/** The table `experience_held_decisions`. */
export interface ExperienceHeldDecisionsRow {
  id: string;
  experience_id: number;
  part_kind: string | null;
  part_ref: string | null;
  part_name: string | null;
  field: string;
  answer: string;
  value: unknown;
  decided_by: number | null;
  decided_at: Date;
}

/** The table `experience_kind_memberships`. */
export interface ExperienceKindMembershipsRow {
  id: number;
  experience_id: number;
  kind_id: number;
  source_id: number;
  admission: string;
  admission_reason: string | null;
  admitted_for: unknown | null;
  is_iconic: boolean;
  curated_fields: unknown;
  curation_state: string;
  published_at: Date | null;
  pending_change_sync_log_id: number | null;
  created_at: Date;
  updated_at: Date;
}

/** The table `experience_kinds`. */
export interface ExperienceKindsRow {
  id: number;
  name: string;
  display_priority: number;
  created_at: Date | null;
}

/** The table `experience_location_regions`. */
export interface ExperienceLocationRegionsRow {
  id: number;
  location_id: number;
  region_id: number;
  assignment_type: string | null;
  created_at: Date | null;
}

/** The table `experience_locations`. */
export interface ExperienceLocationsRow {
  id: number;
  experience_id: number;
  name: string | null;
  external_ref: string | null;
  ordinal: number | null;
  location: string;
  created_at: Date | null;
  missing_since: Date | null;
  curation_state: string;
  refused_at: Date | null;
  curated_fields: unknown;
  withdrawal_deferred_for_location_id: number | null;
  source_membership: string;
  existence: string;
  state_decided_by: number | null;
  state_decided_at: Date | null;
  state_note: string | null;
}

/** The table `experience_regions`. */
export interface ExperienceRegionsRow {
  id: number;
  experience_id: number;
  region_id: number;
  assignment_type: string | null;
  assigned_by: number | null;
  created_at: Date | null;
}

/** The table `experience_rejections`. */
export interface ExperienceRejectionsRow {
  id: number;
  experience_id: number;
  region_id: number;
  rejected_by: number;
  reason: string | null;
  created_at: Date | null;
}

/** The table `experience_sources`. */
export interface ExperienceSourcesRow {
  id: number;
  name: string;
  description: string | null;
  api_endpoint: string | null;
  api_config: unknown | null;
  is_active: boolean | null;
  last_sync_at: Date | null;
  last_sync_status: string | null;
  last_sync_error: string | null;
  display_priority: number;
  kind_id: number;
  created_at: Date | null;
  new_badge_days: number;
  requires_curation: boolean;
}

/** The table `experience_sync_changes`. */
export interface ExperienceSyncChangesRow {
  id: string;
  sync_log_id: number;
  experience_id: number | null;
  external_id: string;
  name_snapshot: string | null;
  change_type: string;
  changed_fields: unknown | null;
  contents: unknown | null;
  significance: string | null;
  error: string | null;
  created_at: Date | null;
}

/** The table `experience_sync_logs`. */
export interface ExperienceSyncLogsRow {
  id: number;
  source_id: number;
  started_at: Date | null;
  completed_at: Date | null;
  status: string | null;
  total_fetched: number | null;
  total_created: number | null;
  total_updated: number | null;
  total_errors: number | null;
  error_details: unknown | null;
  triggered_by: number | null;
  created_at: Date | null;
  total_unchanged: number | null;
  total_missing: number | null;
  total_curated_conflicts: number | null;
  is_dry_run: boolean;
  detection_skipped_reason: string | null;
  total_filtered: number | null;
  total_held: number | null;
  withdrawal_skipped_reason: string | null;
}

/** The table `experience_treasures`. */
export interface ExperienceTreasuresRow {
  id: number;
  experience_id: number;
  treasure_id: number;
  created_at: Date | null;
  curation_state: string;
  refused_at: Date | null;
  missing_since: Date | null;
}

/** The table `experiences`. */
export interface ExperiencesRow {
  id: number;
  source_id: number;
  external_id: string;
  name: string;
  name_local: unknown | null;
  description: string | null;
  short_description: string | null;
  type: string | null;
  tags: unknown | null;
  location: string;
  boundary: string | null;
  area_km2: number | null;
  country_codes: string[] | null;
  country_names: string[] | null;
  image_url: string | null;
  metadata: unknown | null;
  is_manual: boolean;
  created_by: number | null;
  curated_fields: unknown | null;
  status: string;
  created_at: Date | null;
  updated_at: Date | null;
  last_seen_sync_log_id: number | null;
  last_seen_at: Date | null;
  first_seen_sync_log_id: number | null;
  missing_since: Date | null;
  source_membership: string;
  existence: string;
  state_decided_by: number | null;
  state_decided_at: Date | null;
  state_note: string | null;
}

/** The table `import_runs`. */
export interface ImportRunsRow {
  id: number;
  world_view_id: number | null;
  source_type: string;
  status: string | null;
  data_path: string | null;
  stats: unknown | null;
  started_at: Date | null;
  completed_at: Date | null;
}

/** The table `refresh_tokens`. */
export interface RefreshTokensRow {
  id: number;
  user_id: number;
  token_hash: string;
  family_id: string | null;
  expires_at: Date;
  created_at: Date | null;
  revoked_at: Date | null;
}

/** The table `region_geom_pieces`. */
export interface RegionGeomPiecesRow {
  region_id: number;
  geom: string;
}

/** The table `region_import_state`. */
export interface RegionImportStateRow {
  region_id: number;
  import_run_id: number | null;
  source_url: string | null;
  source_external_id: string | null;
  match_status: string;
  needs_manual_fix: boolean | null;
  fix_note: string | null;
  region_map_url: string | null;
  map_image_reviewed: boolean | null;
  marker_points: unknown | null;
  geo_available: boolean | null;
  hierarchy_reviewed: boolean;
  hierarchy_warnings: string[] | null;
}

/** The table `region_map_images`. */
export interface RegionMapImagesRow {
  id: number;
  region_id: number;
  image_url: string;
}

/** The table `region_match_suggestions`. */
export interface RegionMatchSuggestionsRow {
  id: number;
  region_id: number;
  division_id: number;
  name: string;
  path: string | null;
  score: number | null;
  rejected: boolean | null;
  conflict_type: string | null;
  donor_region_id: number | null;
  donor_division_id: number | null;
  donor_region_name: string | null;
  donor_division_name: string | null;
  geo_similarity: number | null;
}

/** The view `region_member_effective_geom`. */
export interface RegionMemberEffectiveGeomRow {
  id: number | null;
  region_id: number | null;
  division_id: number | null;
  geom: string | null;
  is_partial: boolean | null;
  name: string | null;
  division_name: string | null;
}

/** The table `region_members`. */
export interface RegionMembersRow {
  id: number;
  region_id: number;
  division_id: number;
  custom_geom: string | null;
  custom_name: string | null;
  created_at: Date | null;
}

/** The view `region_render_geom`. */
export interface RegionRenderGeomRow {
  id: number | null;
  world_view_id: number | null;
  render_geom: string | null;
  real_geom: string | null;
  uses_hull: boolean | null;
  is_custom_boundary: boolean | null;
  anchor_point: string | null;
  focus_bbox: number[] | null;
}

/** The table `regions`. */
export interface RegionsRow {
  id: number;
  world_view_id: number;
  name: string;
  description: string | null;
  parent_region_id: number | null;
  color: string | null;
  geom: string | null;
  is_custom_boundary: boolean | null;
  anchor_point: string | null;
  geom_area_km2: number | null;
  uses_hull: boolean | null;
  is_leaf: boolean;
  hull_geom: string | null;
  hull_params: unknown | null;
  focus_bbox: number[] | null;
  metadata: unknown | null;
  created_at: Date | null;
  geom_3857: string | null;
  hull_geom_3857: string | null;
  geom_simplified_low: string | null;
  geom_simplified_medium: string | null;
  geom_simplified_coarse: string | null;
  geom_overview: string | null;
  geom_simplified_low_real: string | null;
  geom_simplified_medium_real: string | null;
}

/** The table `schema_migrations`. */
export interface SchemaMigrationsRow {
  filename: string;
  checksum: string;
  ran: boolean;
  applied_at: Date;
}

/** The table `treasures`. */
export interface TreasuresRow {
  id: number;
  external_id: string;
  name: string;
  treasure_type: string;
  year: number | null;
  image_url: string | null;
  sitelinks_count: number;
  is_iconic: boolean;
  metadata: unknown | null;
  created_at: Date | null;
  updated_at: Date | null;
  artists: string[];
  curation_state: string;
  curated_fields: unknown;
}

/** The table `user_auth_providers`. */
export interface UserAuthProvidersRow {
  id: number;
  user_id: number;
  provider: AuthProvider;
  provider_id: string;
  provider_email: string | null;
  provider_data: unknown | null;
  created_at: Date | null;
  updated_at: Date | null;
}

/** The table `user_new_badge_views`. */
export interface UserNewBadgeViewsRow {
  user_id: number;
  experience_id: number;
  first_shown_at: Date;
}

/** The table `user_viewed_treasures`. */
export interface UserViewedTreasuresRow {
  id: number;
  user_id: number;
  treasure_id: number;
  viewed_at: Date | null;
  notes: string | null;
}

/** The table `user_visited_experiences`. */
export interface UserVisitedExperiencesRow {
  id: number;
  user_id: number;
  experience_id: number;
  visited_at: Date | null;
  notes: string | null;
  rating: number | null;
}

/** The table `user_visited_locations`. */
export interface UserVisitedLocationsRow {
  id: number;
  user_id: number;
  location_id: number;
  visited_at: Date | null;
  notes: string | null;
}

/** The table `user_visited_regions`. */
export interface UserVisitedRegionsRow {
  id: number;
  user_id: number;
  region_id: number;
  visited_at: Date | null;
  notes: string | null;
}

/** The table `users`. */
export interface UsersRow {
  id: number;
  uuid: string;
  display_name: string | null;
  email: string | null;
  password_hash: string | null;
  role: UserRole;
  avatar_url: string | null;
  auth_provider: AuthProvider | null;
  provider_id: string | null;
  email_verified: boolean;
  created_at: Date | null;
  last_seen_at: Date | null;
}

/** The table `wikidata_cache_policy`. */
export interface WikidataCachePolicyRow {
  source_id: number;
  kind: string;
  ttl_ms: string;
  updated_at: Date;
}

/** The table `wikidata_geoshapes`. */
export interface WikidataGeoshapesRow {
  wikidata_id: string;
  geom: string | null;
  not_available: boolean;
}

/** The table `wikidata_query_cache`. */
export interface WikidataQueryCacheRow {
  id: number;
  source_id: number;
  query_hash: string;
  kind: string;
  label: string;
  query_text: string;
  result: unknown;
  row_count: number;
  fetched_at: Date;
  expires_at: Date;
}

/** The table `world_views`. */
export interface WorldViewsRow {
  id: number;
  name: string;
  description: string | null;
  source: string | null;
  source_type: string | null;
  is_default: boolean | null;
  is_active: boolean | null;
  last_assignment_at: Date | null;
  tile_version: number | null;
  dismissed_coverage_ids: number[] | null;
  created_at: Date | null;
  updated_at: Date | null;
  is_public: boolean;
}

/**
 * The declared width of every VARCHAR and CHAR column, per element for an
 * array. A request field that lands in one of these is bounded by this
 * number and nothing else, so the bound and the column cannot disagree.
 */
export const COLUMN_WIDTHS = {
  administrative_divisions: {
    name: 255,
  },
  ai_learned_rules: {
    feature: 100,
  },
  ai_settings: {
    key: 255,
  },
  ai_usage_log: {
    feature: 100,
    model: 100,
  },
  curator_assignments: {
    scope_type: 20,
  },
  data_assertion_acceptances: {
    assertion_id: 80,
  },
  email_verification_tokens: {
    token_hash: 255,
  },
  experience_conflict_decisions: {
    field: 100,
  },
  experience_curation_log: {
    action: 30,
  },
  experience_held_decisions: {
    part_kind: 20,
    part_ref: 255,
    part_name: 500,
    field: 100,
    answer: 10,
  },
  experience_kind_memberships: {
    admission: 10,
    curation_state: 10,
  },
  experience_kinds: {
    name: 255,
  },
  experience_location_regions: {
    assignment_type: 20,
  },
  experience_locations: {
    name: 500,
    external_ref: 255,
    curation_state: 10,
    source_membership: 10,
    existence: 10,
  },
  experience_regions: {
    assignment_type: 20,
  },
  experience_sources: {
    name: 255,
    api_endpoint: 1000,
    last_sync_status: 50,
  },
  experience_sync_changes: {
    external_id: 255,
    name_snapshot: 500,
    change_type: 20,
    significance: 10,
  },
  experience_sync_logs: {
    status: 50,
  },
  experience_treasures: {
    curation_state: 10,
  },
  experiences: {
    external_id: 255,
    name: 500,
    type: 100,
    country_codes: 10,
    country_names: 255,
    image_url: 1000,
    status: 20,
    source_membership: 10,
    existence: 10,
  },
  import_runs: {
    source_type: 50,
    status: 20,
  },
  refresh_tokens: {
    token_hash: 255,
    family_id: 64,
  },
  region_import_state: {
    match_status: 30,
  },
  region_member_effective_geom: {
    name: 255,
    division_name: 255,
  },
  region_members: {
    custom_name: 255,
  },
  regions: {
    name: 255,
    description: 1000,
    color: 7,
  },
  treasures: {
    external_id: 255,
    name: 500,
    treasure_type: 50,
    image_url: 1000,
    artists: 500,
    curation_state: 10,
  },
  user_auth_providers: {
    provider_id: 255,
    provider_email: 255,
  },
  users: {
    uuid: 36,
    display_name: 255,
    email: 255,
    password_hash: 255,
    avatar_url: 1000,
    provider_id: 255,
  },
  world_views: {
    name: 255,
    description: 1000,
    source: 1000,
    source_type: 50,
  },
} as const;

/**
 * Every CHECK constraint that is a value list on one column, in the order
 * the schema declares the values. A TypeScript home of the same vocabulary
 * reads it from here (`CheckValue`) rather than restating it.
 */
export const CHECK_VALUES = {
  curator_assignments: {
    scope_type: ["region", "source", "global"],
  },
  experience_curation_log: {
    action: ["created", "rejected", "unrejected", "edited", "added_to_region", "removed_from_region", "marked_former", "marked_lost", "state_restored", "accepted_source", "declined_source", "declined_held", "missing_dismissed", "admission_confirmed", "admission_overridden", "published", "location_marked_former", "location_marked_lost", "location_state_restored", "location_missing_dismissed", "location_edited", "work_edited", "arrival_refused", "contents_refused", "contents_unrefused"],
  },
  experience_held_decisions: {
    answer: ["published", "refused"],
    part_kind: ["locations", "treasures"],
  },
  experience_kind_memberships: {
    admission: ["admitted", "refused"],
    curation_state: ["pending", "auto", "verified"],
  },
  experience_locations: {
    curation_state: ["pending", "auto", "verified"],
    existence: ["extant", "lost"],
    source_membership: ["present", "former"],
  },
  experience_sync_changes: {
    change_type: ["created", "updated", "conflict", "held", "contents", "missing", "returned", "failed", "filtered"],
    significance: ["major", "minor"],
  },
  experience_treasures: {
    curation_state: ["pending", "auto", "verified"],
  },
  experiences: {
    existence: ["extant", "lost"],
    source_membership: ["present", "former"],
    status: ["active", "draft", "archived"],
  },
  treasures: {
    curation_state: ["pending", "auto", "verified"],
  },
} as const;

/** The union a CHECK value list allows: `CheckValue<'experience_sync_changes', 'change_type'>`. */
export type CheckValue<
  T extends keyof typeof CHECK_VALUES,
  C extends keyof (typeof CHECK_VALUES)[T],
> = (typeof CHECK_VALUES)[T][C] extends readonly (infer V)[] ? V : never;
