/**
 * The pure half of the response-type generator (ADR-0066): JSON Schema in,
 * the text of `packages/shared/src/api.generated.ts` out.
 *
 * `generateApiTypes.ts` hands over what `z.toJSONSchema` makes of the response
 * schemas, one entry per exported schema. What arrives is JSON Schema 2020-12,
 * the dialect of OpenAPI 3.1's components, so the web's types are rendered from
 * the same document a native client will one day be generated from.
 *
 * The input is a closed subset, and anything outside it throws rather than
 * rendering as a guess. In particular the renderer refuses:
 * - an object that admits keys it does not declare. `z.object` strips such a
 *   key during the parse, so the check passes while the body still sends the
 *   key. Only `z.strictObject` renders.
 * - a named schema that is a bare string, number or boolean. The name adds
 *   nothing, and the shared package's lint refuses the alias.
 * - a property key that is not an identifier, and a `$ref` to a schema that was
 *   not exported.
 *
 * Deterministic: declarations are sorted by name, so two runs over the same
 * schemas are byte-identical and the freshness spec's comparison is about the
 * schemas alone.
 */

/** One JSON Schema node as `z.toJSONSchema` emits it. */
export type JsonSchema = Readonly<Record<string, unknown>>;

/** Where a `$ref` points: the id a schema was registered under, last. */
export const REF_PREFIX = '#/components/schemas/';

/** Keywords that constrain a value without changing its TypeScript type. */
const IGNORED = new Set([
  '$schema', '$id', 'format', 'pattern',
  'minimum', 'maximum', 'exclusiveMinimum', 'exclusiveMaximum',
  'minLength', 'maxLength', 'minItems', 'maxItems',
]);

/** Every keyword the renderer reads. Any other one throws. */
const KNOWN = new Set([
  ...IGNORED, 'description', '$ref', 'type', 'enum', 'const', 'anyOf', 'oneOf',
  'items', 'prefixItems', 'properties', 'required', 'additionalProperties', 'propertyNames',
]);

const IDENTIFIER = /^[A-Za-z_$][\w$]*$/;
const PRIMITIVES = new Set(['string', 'number', 'integer', 'boolean', 'null']);

const HEADER = `/**
 * GENERATED by backend/src/api/generateApiTypes.ts from the response schemas in
 * backend/src/api/responses/ (ADR-0066). Do not edit: run
 * \`npm --prefix backend run api:types\` after changing a schema. A backend spec
 * fails while this file is not what the schemas render to.
 *
 * Each type is the wire shape of a success body, meaning what \`JSON.parse\`
 * yields on the client. A timestamp is an ISO string, and an absent optional
 * key is absent. The backend holds every body to its schema before sending it
 * outside production, so these types describe what arrives rather than what
 * one would like.
 */
`;

class RenderError extends Error {
  constructor(where: string, what: string) {
    super(`apiTypesRender: ${where} ${what}`);
    this.name = 'RenderError';
  }
}

/** The whole of `api.generated.ts`, from the registered schemas by name. */
export function renderApiTypes(schemas: Readonly<Record<string, JsonSchema>>): string {
  const names = Object.keys(schemas).sort((a, b) => a.localeCompare(b));
  const known = new Set(names);
  const blocks = names.map((name) => renderDeclaration(name, schemas[name], known));
  return `${HEADER}\n${blocks.join('\n\n')}\n`;
}

function renderDeclaration(name: string, schema: JsonSchema, known: ReadonlySet<string>): string {
  if (!IDENTIFIER.test(name)) throw new RenderError(name, 'is not an identifier, so it cannot name a type');
  checkKeywords(schema, name);
  const doc = jsDoc(schema.description, '');
  if (schema.type === 'object' && schema.properties !== undefined) {
    // An object that declares no key is `Record<string, never>`, which is a
    // type and not an interface body.
    const body = renderObject(schema, name, known, '');
    return Object.keys(schema.properties as object).length === 0
      ? `${doc}export type ${name} = ${body};`
      : `${doc}export interface ${name} ${body}`;
  }
  if (typeof schema.type === 'string' && PRIMITIVES.has(schema.type) && schema.enum === undefined && schema.const === undefined) {
    throw new RenderError(name, `is a bare ${schema.type}: a name adds nothing to it, so give it none`);
  }
  return `${doc}export type ${name} = ${renderType(schema, name, known, '')};`;
}

function checkKeywords(schema: JsonSchema, where: string): void {
  for (const keyword of Object.keys(schema)) {
    if (!KNOWN.has(keyword)) throw new RenderError(where, `uses \`${keyword}\`, which this renderer does not read`);
  }
}

function renderType(schema: JsonSchema, where: string, known: ReadonlySet<string>, indent: string): string {
  checkKeywords(schema, where);
  if (typeof schema.$ref === 'string') return refName(schema.$ref, where, known);
  if (schema.const !== undefined) return literal(schema.const, where);
  if (Array.isArray(schema.enum)) return schema.enum.map((value) => literal(value, where)).join(' | ');
  const members = schema.anyOf ?? schema.oneOf;
  if (Array.isArray(members)) {
    return members.map((member, i) => renderType(member as JsonSchema, `${where}|${i}`, known, indent)).join(' | ');
  }
  switch (schema.type) {
    case 'string': return 'string';
    case 'number':
    case 'integer': return 'number';
    case 'boolean': return 'boolean';
    case 'null': return 'null';
    case 'array': return renderArray(schema, where, known, indent);
    case 'object': return renderObjectType(schema, where, known, indent);
    case undefined:
      // `{}` is what `z.unknown()` becomes: any JSON value at all.
      if (Object.keys(schema).every((keyword) => keyword === 'description')) return 'unknown';
      throw new RenderError(where, 'has no type this renderer knows');
    default:
      throw new RenderError(where, `has type ${JSON.stringify(schema.type)}, which this renderer does not render`);
  }
}

function renderArray(schema: JsonSchema, where: string, known: ReadonlySet<string>, indent: string): string {
  if (Array.isArray(schema.prefixItems)) return renderTuple(schema, where, known, indent);
  if (typeof schema.items !== 'object' || schema.items === null) {
    throw new RenderError(where, 'is an array without one `items` schema');
  }
  const items = schema.items as JsonSchema;
  const item = renderType(items, `${where}[]`, known, indent);
  return isUnion(items) ? `(${item})[]` : `${item}[]`;
}

/**
 * A `z.tuple`: one schema per position, which Zod emits as `prefixItems` and
 * nothing else. A rest element would come as `items` beside them, and no answer
 * has one yet.
 */
function renderTuple(schema: JsonSchema, where: string, known: ReadonlySet<string>, indent: string): string {
  if (schema.items !== undefined) throw new RenderError(where, 'is a tuple with a rest element, which this renderer does not render');
  const positions = (schema.prefixItems as JsonSchema[]).map((item, i) => renderType(item, `${where}[${i}]`, known, indent));
  return `[${positions.join(', ')}]`;
}

/** Whether a schema renders as `A | B`, which an array suffix would otherwise bind to the last member only. */
function isUnion(schema: JsonSchema): boolean {
  const members = schema.anyOf ?? schema.oneOf;
  if (typeof schema.$ref === 'string') return false;
  return (Array.isArray(members) && members.length > 1) || (Array.isArray(schema.enum) && schema.enum.length > 1);
}

function renderObjectType(schema: JsonSchema, where: string, known: ReadonlySet<string>, indent: string): string {
  if (schema.properties !== undefined) return renderObject(schema, where, known, indent);
  // A record: `z.record(z.string(), X)`, keys of any string, each value an X.
  const values = schema.additionalProperties;
  if (typeof values !== 'object' || values === null) {
    throw new RenderError(where, 'is an object with neither properties nor a value schema for its keys');
  }
  const names = schema.propertyNames as JsonSchema | undefined;
  if (names !== undefined && !(names.type === 'string' && Object.keys(names).length === 1)) {
    throw new RenderError(where, 'restricts its keys, which this renderer does not render');
  }
  const value = renderType(values as JsonSchema, where + '{}', known, indent);
  return `Record<string, ${value}>`;
}

function renderObject(schema: JsonSchema, where: string, known: ReadonlySet<string>, indent: string): string {
  if (schema.additionalProperties !== false) {
    throw new RenderError(where, 'admits keys it does not declare; a response object is a `z.strictObject`');
  }
  const properties = schema.properties as Readonly<Record<string, JsonSchema>>;
  const required = new Set(Array.isArray(schema.required) ? (schema.required as string[]) : []);
  const inner = `${indent}  `;
  const lines = Object.entries(properties).map(([key, property]) => {
    if (!IDENTIFIER.test(key)) throw new RenderError(`${where}.${key}`, 'is not an identifier');
    const optional = required.has(key) ? '' : '?';
    const type = renderType(property, `${where}.${key}`, known, inner);
    return `${jsDoc(property.description, inner)}${inner}${key}${optional}: ${type};`;
  });
  return lines.length === 0 ? 'Record<string, never>' : `{\n${lines.join('\n')}\n${indent}}`;
}

function refName(ref: string, where: string, known: ReadonlySet<string>): string {
  const name = ref.startsWith(REF_PREFIX) ? ref.slice(REF_PREFIX.length) : '';
  if (!known.has(name)) throw new RenderError(where, `refers to ${ref}, which no exported schema is`);
  return name;
}

function literal(value: unknown, where: string): string {
  if (value === null || ['string', 'number', 'boolean'].includes(typeof value)) return JSON.stringify(value);
  throw new RenderError(where, `holds a literal ${JSON.stringify(value)} that is not a JSON scalar`);
}

/** The widest a rendered comment line gets, indentation included. */
const COMMENT_WIDTH = 100;

/**
 * A description as JSDoc: one line when it fits, otherwise wrapped at word
 * boundaries. `*\/` is escaped so a description cannot close its comment early.
 */
function jsDoc(description: unknown, indent: string): string {
  if (typeof description !== 'string' || description.trim() === '') return '';
  const text = description.trim().replaceAll('*/', '*\\/');
  if (!text.includes('\n') && indent.length + text.length + 7 <= COMMENT_WIDTH) return `${indent}/** ${text} */\n`;
  const width = COMMENT_WIDTH - indent.length - 3;
  const lines = text.split('\n').flatMap((paragraph) => wrap(paragraph, width));
  const body = lines.map((line) => (line === '' ? `${indent} *` : `${indent} * ${line}`)).join('\n');
  return `${indent}/**\n${body}\n${indent} */\n`;
}

/** Words of `paragraph` in lines of at most `width`; a word longer than that gets a line of its own. */
function wrap(paragraph: string, width: number): string[] {
  const lines: string[] = [];
  let line = '';
  for (const word of paragraph.split(/\s+/).filter(Boolean)) {
    if (line !== '' && line.length + 1 + word.length > width) {
      lines.push(line);
      line = word;
    } else {
      line = line === '' ? word : `${line} ${word}`;
    }
  }
  lines.push(line);
  return lines;
}
