/**
 * GENERATED by backend/src/api/generateApiTypes.ts from the response schemas in
 * backend/src/api/responses/ (ADR-0066). Do not edit: run
 * `npm --prefix backend run api:types` after changing a schema. A backend spec
 * fails while this file is not what the schemas render to.
 *
 * Each type is the wire shape of a success body, meaning what `JSON.parse`
 * yields on the client. A timestamp is an ISO string, and an absent optional
 * key is absent. The backend holds every body to its schema before sending it
 * outside production, so these types describe what arrives rather than what
 * one would like.
 */

/** What taking the source's value for claimed fields did. */
export interface AcceptSourceResult {
  /** Set when the publication landed and re-placing the object into its regions did not. */
  placementFailed?: true;
  /**
   * Where the regions are stale now. Present exactly when `placementFailed` is, and never empty.
   */
  placementFailedWorldViews?: PlacementFailure[];
  experienceId: number;
  /** The fields now holding the source's value. */
  applied: string[];
  /** The claims given up to take it. */
  released: string[];
  /**
   * The points whose own claim on the coordinate went with the object's, because the object's
   * coordinate and its one visible point's are the same fact.
   */
  releasedPoints: number[];
  /** Those of them also put back on the coordinate the run offered. */
  movedPoints: number[];
  /**
   * Whether taking the source's picture also dropped the credit the curator's own edit wrote for
   * it.
   */
  releasedCredit: boolean;
  /** The run whose proposal was taken. */
  fromSyncLogId: number;
}

/** What answering a refusal did. */
export interface AdmissionResult {
  experienceId: number;
  /** The object's own state after the call, unchanged when `published` is false. */
  curationState: MembershipCurationState;
  /** Always empty: an override never applies a held field. */
  appliedFields: string[];
  /** Always empty, for the same reason. */
  claimedFieldsSkipped: string[];
  /** Always empty: a held field of a part is a proposal too, and an override answers none. */
  appliedParts: AppliedPart[];
  /** Always null, for the same reason. */
  fromSyncLogId: null;
  /**
   * Always zero: an override answers no held row, so it leaves none open either. A row holding a
   * proposal keeps its pointer and its own card through an override.
   */
  heldLeftOpen: 0;
  /** Points shown to readers now. */
  locationsPublished: number;
  /** Links to the object's works shown to readers now. */
  treasureLinksPublished: number;
  /** Works shown to readers now. */
  treasuresPublished: number;
  /** Points the source had replaced, no longer shown now that their replacement is. */
  withdrawalsReleased: number;
  /** Set when the publication landed and re-placing the object into its regions did not. */
  placementFailed?: true;
  /**
   * Where the regions are stale now. Present exactly when `placementFailed` is, and never empty.
   */
  placementFailedWorldViews?: PlacementFailure[];
  /** The verdict now standing: `admitted` after an override, `refused` after a confirm. */
  admission: "admitted" | "refused";
  /**
   * Whether this override also made the object visible. True only where the object was unread and
   * the verdict was `override`: putting a gated arrival back is what publishes it (ADR-0025), while
   * overriding the refusal of a visible object says nothing about whether anyone has read it.
   */
  published: boolean;
}

/** Every place of an object, or of it within a region, marked visited. */
export interface AllLocationsMarked {
  success: true;
  experienceId: number;
  /** The region the marking was limited to, or null for the whole object. */
  regionId: number | null;
  locationsMarked: number;
}

/** Every place of an object, or of it within a region, no longer marked visited. */
export interface AllLocationsUnmarked {
  success: true;
  experienceId: number;
  regionId: number | null;
  locationsUnmarked: number;
}

/** A lost point a curator has answered, which no reader sees as a result (#544). */
export interface AnsweredPoint {
  id: number;
  name: string | null;
  externalRef: string | null;
  /** Null where a later run found the point again and cleared the flag. */
  missingSince: string | null;
  latitude: number | null;
  longitude: number | null;
  sourceMembership: "present" | "former";
  existence: "extant" | "lost";
  decidedAt: string | null;
  note: string | null;
  /**
   * Who last decided, read from the curation log under the log's own scope. Null where the act
   * belongs to a region this reader does not cover, or predates the log.
   */
  decidedBy: string | null;
  visited: boolean;
  curatedFields?: string[];
}

/** One part publishing wrote to, such as a place renamed or a work re-attributed (ADR-0037). */
export interface AppliedPart {
  kind: ContentKind;
  /** The part as the record names it, which is what the curator saw on the card. */
  name: string;
  /** The held fields written to the part now. */
  fields: string[];
  /** Held fields left as the curator wrote them, because the part's own claims hold them. */
  claimedFieldsSkipped: string[];
}

/** One field a run proposed to change. */
export interface ChangedField {
  field: string;
  /** The stored value the run found. Absent where there was none. */
  old: unknown;
  /** The value the source offered. */
  new: unknown;
  significance?: "major" | "minor";
  /** A curator had claimed the field, so the stored value won on purpose. */
  curatedConflict?: boolean;
  /**
   * The source's gate kept the write out of a row readers see, so a verdict is waiting (ADR-0025).
   */
  held?: boolean;
}

/**
 * Which of an object's contents a part is: one of its points (`locations`) or one of its works
 * (`treasures`).
 */
export type ContentKind = "locations" | "treasures";

/** A famous work the kind's rule weighed. */
export interface CountedWork {
  name: string;
  type: string | null;
  artists: string[];
  artistsCurated: boolean;
  imageUrl: string | null;
  imageCredit?: ImageCredit | null;
  year: number | null;
  /** The source's own id for the work: a Wikidata QID for everything stored today. */
  externalId: string;
}

/** The newest fifty acts on the object that the curator may see, newest first. */
export type CurationLog = CurationLogEntry[];

/** One act of the object's curation log. */
export interface CurationLogEntry {
  id: number;
  action: "created" | "rejected" | "unrejected" | "edited" | "added_to_region" | "removed_from_region" | "marked_former" | "marked_lost" | "state_restored" | "accepted_source" | "declined_source" | "declined_held" | "missing_dismissed" | "admission_confirmed" | "admission_overridden" | "published" | "location_marked_former" | "location_marked_lost" | "location_state_restored" | "location_missing_dismissed" | "location_edited" | "work_edited" | "arrival_refused" | "contents_refused" | "contents_unrefused";
  region_id: number | null;
  region_name: string | null;
  /** What the act changed, in the shape its action writes. */
  details: Record<string, unknown> | null;
  created_at: string | null;
  /** The curator as they chose to be named, null where they chose nothing. */
  curator_name: string | null;
}

/** One part a refusal of held rows reached. */
export interface DeclinedPart {
  kind: ContentKind;
  /** The part as the record names it. */
  name: string;
  fields: string[];
}

/** What refusing held rows of a gated proposal settled. */
export interface DeclineHeldResult {
  experienceId: number;
  /** The object's own fields refused now. */
  declinedFields: string[];
  /** The parts refused now, grouped as the card grouped them. */
  declinedParts: DeclinedPart[];
  fromSyncLogId: number;
  /** Held rows still open. Zero means the card is gone and the pointer with it. */
  heldLeftOpen: number;
}

/** What standing by the curator's own value did. */
export interface DeclineSourceResult {
  experienceId: number;
  /** The fields whose proposal was turned down, the curator's value kept. */
  declined: string[];
  fromSyncLogId: number;
}

/** An earlier answer on the same field. */
export interface EarlierAnswer {
  by: string;
  at: string;
  /** Which answer it was. Absent on rows written before refusing was possible. */
  action?: "accepted_source" | "declined_source";
  /** What that answer was about: the value taken, or the one refused. */
  applied: unknown;
}

/** One object in a region's list. */
export interface Experience {
  id: number;
  external_id: string;
  name: string;
  short_description: string | null;
  /**
   * The type within the kind, such as `cultural` on a World Heritage site or `cathedral` on a place
   * of worship. Null on a museum, whose kind has no types (ADR-0045).
   */
  type: string | null;
  /** The kind, off the row's membership (#819): what a colour and a group are decided by. */
  kind_id: number;
  /** Null on a place created by hand without a country, which the columns allow. */
  country_codes: string[] | null;
  country_names: string[] | null;
  image_url: string | null;
  /**
   * Whose photograph this is, beside the picture because a thumbnail in a list is showing it
   * (ADR-0043).
   */
  image_credit: ImageCredit | null;
  in_danger: boolean;
  /** The year the site was listed in danger. Null where the listing carries no year. */
  danger_since: number | null;
  longitude: number;
  latitude: number;
  kind_name: string;
  /** The kind's display order, which the list orders by. */
  kind_priority: number;
  location_count: number;
  /** Offered and published links to works. */
  treasure_count: number;
  created_at?: string;
  /** Only for a curator whose scope reaches the region. */
  is_rejected?: boolean;
  rejection_reason?: string | null;
  source_membership: "present" | "former";
  existence: "extant" | "lost";
  missing_since: string | null;
  /**
   * Whether the reader could first see this recently: published, and inside the kind's window or
   * this reader's own week (#529).
   */
  is_new: boolean;
}

/** One object, as its own page reads it. */
export interface ExperienceDetail {
  id: number;
  /** The source that brought the row, beside the kind it is shown under. */
  source_id: number;
  external_id: string;
  name: string;
  name_local: Record<string, string> | null;
  description: string | null;
  short_description: string | null;
  type: string | null;
  /** Null on a place created by hand without a country, which the columns allow. */
  country_codes: string[] | null;
  country_names: string[] | null;
  image_url: string | null;
  /** The source's metadata, as an open record until #574 settles its model. */
  metadata: Record<string, unknown> | null;
  created_at: string | null;
  updated_at: string | null;
  source_membership: "present" | "former";
  existence: "extant" | "lost";
  missing_since: string | null;
  longitude: number;
  latitude: number;
  /** The site's extent from OpenStreetMap, simplified past 5,000 vertices (ADR-0059). */
  boundary_geojson: {
    type: "MultiPolygon";
    coordinates: number[][][][];
  } | null;
  area_km2: number | null;
  kind_id: number;
  kind_name: string;
  kind_priority: number;
  source_name: string;
  source_description: string | null;
  /** The regions whose own lists hold the object, in the world views the caller may see. */
  regions: ExperienceRegionRef[];
}

/** What a curator's edit of an object's fields did. */
export interface ExperienceEditResult {
  success: true;
  experienceId: number;
  /** Every field the curator now claims on the object, this edit's included. */
  curatedFields: string[];
}

/** A kind of place a traveller browses by (ADR-0045). */
export interface ExperienceKind {
  id: number;
  name: string;
  display_priority: number;
  /** How many places the kind offers. A string: PostgreSQL counts in bigint. */
  experience_count: string;
}

/** The kinds a source fills today, in display order. */
export type ExperienceKinds = ExperienceKind[];

/** One point of an object. */
export interface ExperienceLocation {
  id: number;
  experience_id: number;
  /** The component the source names, such as one fort of a serial nomination. */
  name: string | null;
  /** The source's own reference, such as `1739-005` for UNESCO. */
  external_ref: string | null;
  /**
   * The point's place in the source's list. Null for a point waiting on its replacement to be
   * published, and sorted last. Read it through `locationLabel` rather than doing arithmetic on it.
   */
  ordinal: number | null;
  longitude: number;
  latitude: number;
  created_at: string | null;
  /**
   * The fields a curator has claimed on the point, such as `name` and `location`, so a row can say
   * it is corrected.
   */
  curated_fields: string[];
  /** Whether the point lies in the region the read was asked about. True where none was named. */
  in_region: boolean;
}

/** An object's own points. */
export interface ExperienceLocationsResponse {
  experienceId: number;
  experienceName: string;
  /** In the source's order, with the points that have no place last. */
  locations: ExperienceLocationWithState[];
  totalLocations: number;
  /** The region `in_region` was asked about, or null where none was named. */
  regionId: number | null;
}

/** One point as its object's own read serves it, with where it stands at the gate. */
export interface ExperienceLocationWithState {
  id: number;
  experience_id: number;
  /** The component the source names, such as one fort of a serial nomination. */
  name: string | null;
  /** The source's own reference, such as `1739-005` for UNESCO. */
  external_ref: string | null;
  /**
   * The point's place in the source's list. Null for a point waiting on its replacement to be
   * published, and sorted last. Read it through `locationLabel` rather than doing arithmetic on it.
   */
  ordinal: number | null;
  longitude: number;
  latitude: number;
  created_at: string | null;
  /**
   * The fields a curator has claimed on the point, such as `name` and `location`, so a row can say
   * it is corrected.
   */
  curated_fields: string[];
  /** Whether the point lies in the region the read was asked about. True where none was named. */
  in_region: boolean;
  curation_state: LocationCurationState;
  /**
   * Set where a curator turned this unread point down. The state cannot say so, because a refused
   * point stays `pending`: publishing shows an unread point and refuses a turned-down one.
   */
  refused_at: string | null;
}

/** A region an object can be opened at, in a world view the caller may see. */
export interface ExperienceRegionRef {
  id: number;
  name: string;
  world_view_id: number;
  world_view_name: string;
}

/** A page of a region's objects. */
export interface ExperiencesByRegionResponse {
  region: {
    id: number;
    name: string;
    world_view_name: string;
  };
  experiences: Experience[];
  total: number;
  /** How many objects this region holds that no longer exist and are not being shown. */
  lostHidden: number;
  limit: number;
  offset: number;
}

/** What the catalogue search found for a name. */
export interface ExperienceSearch {
  query: string;
  results: ExperienceSearchResult[];
  total: number;
}

/** One answer of the catalogue search. */
export interface ExperienceSearchResult {
  id: number;
  name: string;
  short_description: string | null;
  type: string | null;
  kind_id: number;
  kind_name: string;
  kind_priority: number;
  country_names: string[] | null;
  image_url: string | null;
  image_credit: ImageCredit | null;
  source_membership: "present" | "former";
  existence: "extant" | "lost";
  missing_since: string | null;
  longitude: number;
  latitude: number;
  relevance: number;
  /**
   * The regions whose own lists hold the object, most specific first. Empty where nothing published
   * places it, and then the answer is not a link.
   */
  regions: ExperienceRegionRef[];
}

/** An object's lifecycle as a curator's verdict left it. */
export interface ExperienceStateResult {
  experienceId: number;
  /** Whether the source still lists it: `former` once it has delisted it. */
  sourceMembership: "present" | "former";
  /** Whether it is still there to visit: `lost` once it is gone. */
  existence: "extant" | "lost";
}

/** A work inside an object: an artwork, an artifact. */
export interface ExperienceTreasure {
  id: number;
  external_id: string;
  name: string;
  treasure_type: string;
  /** Every maker the source names (#720). */
  artists: string[];
  /** Whether a curator has vouched for the order the makers are stored in (ADR-0040). */
  artists_curated: boolean;
  /** The columns a curator has claimed on the work. */
  curated_fields: string[];
  /** How many museums hang this work (ADR-0025 decision 2). */
  venue_count: number;
  year: number | null;
  image_url: string | null;
  image_credit: ImageCredit | null;
  is_iconic: boolean;
  /** Where the object was dug up, for the kind whose works are finds (ADR-0058). */
  found_at: {
    qid: string;
    label: string;
  } | null;
  /** The site row that spot names, where the catalogue holds one a reader may open (#894). */
  found_at_site: LinkedPlace | null;
  sitelinks_count: number;
}

/** The works an object holds. */
export interface ExperienceTreasuresResponse {
  experienceId: number;
  treasures: ExperienceTreasure[];
  total: number;
}

/** How far through an object's places the reader is, place by place. */
export interface ExperienceVisitedStatusResponse {
  experienceId: number;
  visitedStatus: VisitedStatus;
  totalLocations: number;
  visitedLocations: number;
  locations: LocationWithVisitedStatus[];
}

/** An object marked visited, or its visit renewed. */
export interface ExperienceVisitMarked {
  success: true;
  experienceId: number;
  experienceName: string;
  /** The visit's own row. */
  id: number;
  visited_at: string | null;
  notes: string | null;
  rating: number | null;
}

/** An object no longer marked visited. */
export interface ExperienceVisitUnmarked {
  success: true;
  experienceId: number;
}

/** Who claimed a field, and when. */
export interface FieldClaim {
  /** The curator, or "a curator" where they set no display name. */
  by: string;
  at: string;
}

/**
 * One part of an object whose field a gated run held (ADR-0037), with what the stored row adds. The
 * row's fields are null where no offered row answers to the record.
 */
export interface HeldPart {
  kind: ContentKind;
  /** The part as the record names it: the name as the run saw it, never rewritten (ADR-0026). */
  item: {
    name: string | null;
    ref: string | null;
  };
  /**
   * The stored row's name now, where the row was found, since a part corrected since has another.
   */
  storedName?: string | null;
  /** The held fields of the part. */
  fields: ChangedField[];
  locationId?: number | null;
  /** The fields a curator has claimed on the stored place. */
  curatedFields?: string[] | null;
  latitude?: number | null;
  longitude?: number | null;
  ordinal?: number | null;
  treasureId?: number | null;
  artists?: string[] | null;
  artistsCurated?: boolean | null;
  /** The fields a curator has claimed on the stored work. */
  workCuratedFields?: string[] | null;
  /** How many museums hang the work. */
  venueCount?: number | null;
  year?: number | null;
  imageUrl?: string | null;
  imageCredit?: ImageCredit | null;
  treasureType?: string | null;
}

/** Who a picture is credited to, as `ImageCreditLine` draws it (ADR-0043). */
export interface ImageCredit {
  /** The photographer or uploader, as plain text. */
  author: string | null;
  /** The licence in the words its own name uses: "CC BY-SA 3.0", "Public domain". */
  license: string | null;
  licenseUrl: string | null;
  /** The file page or the site's own page for the object: where the full terms are. */
  detailsUrl: string | null;
}

/** A place another card names, with the regions a link to it is built from (ADR-0042). */
export interface LinkedPlace {
  id: number;
  name: string;
  /** The kind the place is shown under, which Discover's address needs. */
  kind_id: number | null;
  regions: ExperienceRegionRef[];
}

/**
 * Whether readers see the point yet. `pending` is shown to nobody but a curator until it is
 * published. `auto` and `verified` are shown to readers.
 */
export type LocationCurationState = "pending" | "auto" | "verified";

/** What a curator's correction to a place's name or position did. */
export interface LocationEditResult {
  /** Set when the publication landed and re-placing the object into its regions did not. */
  placementFailed?: true;
  /**
   * Where the regions are stale now. Present exactly when `placementFailed` is, and never empty.
   */
  placementFailedWorldViews?: PlacementFailure[];
  success: true;
  locationId: number;
  /**
   * Whether the object's own coordinate moved with the place. True only where the object holds
   * exactly one visible, published place and this is it.
   */
  anchorMoved: boolean;
}

/** A point's lifecycle as a curator's verdict left it. */
export interface LocationStateResult {
  /** Set when the publication landed and re-placing the object into its regions did not. */
  placementFailed?: true;
  /**
   * Where the regions are stale now. Present exactly when `placementFailed` is, and never empty.
   */
  placementFailedWorldViews?: PlacementFailure[];
  locationId: number;
  experienceId: number;
  sourceMembership: "present" | "former";
  existence: "extant" | "lost";
  /**
   * Whether a reader sees the point now. A verdict can move it either way, and both axes decide it,
   * so the answer says it rather than leaving a card to work it out.
   */
  offeredToReaders: boolean;
}

/** A place marked visited, or its visit renewed. */
export interface LocationVisitMarked {
  success: true;
  locationId: number;
  locationName: string | null;
  experienceId: number;
  experienceName: string;
  /** The visit's own row. */
  id: number;
  visited_at: string | null;
  notes: string | null;
}

/** A place no longer marked visited. */
export interface LocationVisitUnmarked {
  success: true;
  locationId: number;
  experienceId: number;
}

/** One place of an object, with whether the reader has been there. */
export interface LocationWithVisitedStatus {
  id: number;
  name: string | null;
  /** Nullable, for the reason given on `ExperienceLocation.ordinal`. */
  ordinal: number | null;
  longitude: number;
  latitude: number;
  isVisited: boolean;
  visitedAt: string | null;
  notes: string | null;
}

/** The object a curator created by hand. */
export interface ManualExperienceCreated {
  id: number;
  name: string;
  /** The id the manual source gave it. */
  externalId: string;
}

/**
 * Where the object stands at the curation gate of its kind. `pending` is shown to nobody but a
 * curator. `auto` and `verified` are shown to readers, `verified` because a person passed it.
 */
export type MembershipCurationState = "pending" | "auto" | "verified";

/** Which New chips were recorded as shown. */
export interface NewBadgesSeen {
  /** The objects whose first impression this call recorded. Only the first is kept. */
  recorded: number[];
}

/**
 * A part the held proposal names that publishing could not write to. Nothing readers see changed.
 */
export interface PartNotFound {
  kind: ContentKind;
  /** The part as the record names it. */
  name: string;
  /**
   * `withdrawn`: no offered row answers to the part any more. `ambiguous`: more than one does, and
   * nothing tells them apart, such as a component listed once per country under one reference.
   */
  reason: "withdrawn" | "ambiguous";
}

/** An unread point under a row readers already see. */
export interface PendingPoint {
  id: number;
  name: string | null;
  externalRef: string | null;
  latitude: number | null;
  longitude: number | null;
  curatedFields?: string[];
}

/** An unread work under a row readers already see. */
export interface PendingWork {
  id: number;
  name: string | null;
  artists: string[];
  artistsCurated: boolean;
  year: number | null;
  imageUrl: string | null;
  iconic: boolean;
  /** The work's own Wikidata id, where the row opens the item from (#806). */
  externalId?: string;
  treasureType?: string | null;
  imageCredit?: ImageCredit | null;
  curatedFields?: string[] | null;
  venueCount?: number | null;
}

/** A world view whose regions the publication could not recompute. */
export interface PlacementFailure {
  /**
   * The world view, or null where listing the world views is what failed, so none was attempted.
   */
  id: number | null;
  name: string | null;
}

/** The tier asked for: `overview` is the heatmap's read, `markers` the pins'. */
export type PointsDetail = "overview" | "markers";

/** One of the object's own fields a run proposed, as its card asks about it. */
export interface ProposedField {
  field: string;
  /** The stored value the run found. Absent where there was none. */
  old: unknown;
  /** The value the source offered. */
  new: unknown;
  significance?: "major" | "minor";
  /** A curator had claimed the field, so the stored value won on purpose. */
  curatedConflict?: boolean;
  /**
   * The source's gate kept the write out of a row readers see, so a verdict is waiting (ADR-0025).
   */
  held?: boolean;
  /**
   * False where accepting releases the claim and the next run writes it. On a `conflict` field
   * only: a `held` field carries `held` instead, and publishing is what applies it.
   */
  acceptable?: boolean;
  /**
   * Who claimed the field. Absent where the claim predates the log, or where the gate holds the
   * field.
   */
  claim?: FieldClaim | null;
  /** Every earlier answer on this field, newest first, refusals as well as acceptances. */
  decidedBefore?: EarlierAnswer[];
}

/** What a publication did, so the page can say it before the refetch. */
export interface PublishResult {
  experienceId: number;
  /** The object's own state after the call. A contents publish leaves it as it was. */
  curationState: MembershipCurationState;
  /** Held fields written now. */
  appliedFields: string[];
  /** Held fields left as the curator wrote them, because the curator claims them. */
  claimedFieldsSkipped: string[];
  /**
   * The parts whose held fields were written now. Empty on a contents publish, which leaves the
   * proposal where it was.
   */
  appliedParts: AppliedPart[];
  /** Parts the proposal names that nothing could be written to. Present only when there is one. */
  partsNotFound?: PartNotFound[];
  /** The run whose held proposal was applied, or null when none was held. */
  fromSyncLogId: number | null;
  /**
   * Held rows this call left open, at both levels. Non-zero exactly when the card is still
   * standing, because the pointer that keys it was kept. Zero on every call that names no
   * selection.
   */
  heldLeftOpen: number;
  /** Points shown to readers now. */
  locationsPublished: number;
  /** Links to the object's works shown to readers now. */
  treasureLinksPublished: number;
  /** Works shown to readers now. */
  treasuresPublished: number;
  /** Points the source had replaced, no longer shown now that their replacement is. */
  withdrawalsReleased: number;
  /** Set when the publication landed and re-placing the object into its regions did not. */
  placementFailed?: true;
  /**
   * Where the regions are stale now. Present exactly when `placementFailed` is, and never empty.
   */
  placementFailedWorldViews?: PlacementFailure[];
}

/** What each chip would leave, counted over the union under every other filter the curator set. */
export interface QueueFacets {
  kind: {
    kind: "conflict" | "waiting" | "withdrawn" | "refused" | "missing" | "arrival" | "held" | "contents";
    count: number;
  }[];
  source: {
    id: number;
    name: string;
    count: number;
  }[];
  region: {
    /** Null is the unplaced bucket: keys with no region row at all. */
    id: number | null;
    name: string;
    /**
     * The world view this root is a root of, null on the unplaced row. A name does not identify a
     * root on its own: two of them are called Europe.
     */
    worldView: string | null;
    count: number;
  }[];
  /**
   * The runs with open questions, counted before the set-aside exclusion, because a hidden batch is
   * exactly the one the chip has to name, or there is no way back to it. The search still narrows
   * this list.
   */
  run: {
    id: number;
    sourceId: number;
    /** Null for a run still in flight. */
    completedAt: string | null;
    count: number;
    /** Whether this curator has already hidden the batch. */
    setAside: boolean;
  }[];
  /** How many runs this curator has set aside, which is the unit the chip names. */
  setAside: {
    batches: number;
  };
}

/** The class of an open question, which a batch answer names a row by. */
export type QueueKind = "conflict" | "waiting" | "withdrawn" | "refused" | "missing";

/** One open question, in the order the page draws them (ADR-0051). */
export interface QueueOrderEntry {
  kind: QueueKind;
  id: number;
  /** When the run that raised this question completed. Null for one still in flight. */
  askedAt: string | null;
  runId: number | null;
  /** The gated sub-kinds a `waiting` row groups. An arrival is always alone. */
  subs: WaitingSub[];
}

/** A curator's no to an arrival (ADR-0053). */
export interface RefuseArrivalResult {
  experienceId: number;
  admission: "refused";
  /** The reason the kept-out list shows. */
  reason: string;
}

/** What turning down the unread points and works of an object did. */
export interface RefuseContentsResult {
  /** Set when the publication landed and re-placing the object into its regions did not. */
  placementFailed?: true;
  /**
   * Where the regions are stale now. Present exactly when `placementFailed` is, and never empty.
   */
  placementFailedWorldViews?: PlacementFailure[];
  experienceId: number;
  locationsRefused: number;
  treasureLinksRefused: number;
  /**
   * Old pins a refused arrival had been holding on the map, now withdrawn and asking their own
   * question.
   */
  withdrawalsReleased: number;
}

/** A point a curator turned down (#859). */
export interface RefusedPoint {
  id: number;
  name: string | null;
  externalRef: string | null;
  latitude: number | null;
  longitude: number | null;
  curatedFields?: string[];
  refusedAt: string | null;
  refusedBy: string | null;
  note: string | null;
  /** Set where the source has stopped listing the point since it was turned down. */
  missingSince: string | null;
  visited: boolean;
}

/** A work link a curator turned down (#859). */
export interface RefusedWork {
  /** The treasure id, which the take-back takes. */
  id: number;
  name: string | null;
  artists: string[];
  artistsCurated: boolean;
  year: number | null;
  externalId?: string;
  curatedFields?: string[] | null;
  refusedAt: string | null;
  refusedBy: string | null;
  note: string | null;
  missingSince: string | null;
}

/** A region's counts per kind, for Discover's tree. */
export interface RegionExperienceCount {
  region_id: number;
  region_name: string;
  region_color: string | null;
  has_subregions: boolean;
  /** How many places each kind counts here, keyed by kind id. */
  kind_counts: Record<string, number>;
}

export type RegionExperienceCounts = RegionExperienceCount[];

/** One point as the map and the region list read it. */
export interface RegionExperienceLocation {
  id: number;
  experience_id: number;
  /** The component the source names, such as one fort of a serial nomination. */
  name: string | null;
  /** The source's own reference, such as `1739-005` for UNESCO. */
  external_ref: string | null;
  /**
   * The point's place in the source's list. Null for a point waiting on its replacement to be
   * published, and sorted last. Read it through `locationLabel` rather than doing arithmetic on it.
   */
  ordinal: number | null;
  longitude: number;
  latitude: number;
  created_at: string | null;
  /**
   * The fields a curator has claimed on the point, such as `name` and `location`, so a row can say
   * it is corrected.
   */
  curated_fields: string[];
  /** Whether the point lies in the region the read was asked about. True where none was named. */
  in_region: boolean;
  /**
   * The leaf region the point lies in, with its ancestors, such as `Europe > France > Paris`. It is
   * shown for a point outside the region on screen. Null where the point lies in no region of that
   * world view.
   */
  region_path: string | null;
}

/** The points of a region's objects, in one read rather than one per object. */
export interface RegionExperienceLocationsResponse {
  /** Every point of every object the region list shows, keyed by the object id. */
  locationsByExperience: Record<string, RegionExperienceLocation[]>;
}

/**
 * What rejecting, unrejecting, assigning, unassigning or removing an object in a region did: it is
 * done.
 */
export interface RegionMembershipResult {
  success: true;
  experienceId: number;
  regionId: number;
}

/** The two answers every review row has, and the third two kinds have (#852). */
export type ReviewAnswer = "accept" | "reject" | "lost";

/** What one answer did, counted. The notice sums these per kind and answer. */
export interface ReviewAnswerDid {
  /** 1 where this answer made the object visible to readers. */
  published?: number;
  locations?: number;
  treasureLinks?: number;
  treasures?: number;
  withdrawalsReleased?: number;
  /**
   * Held or claimed fields this answer applied, released or refused, the parts' rows counted with
   * the object's.
   */
  fields?: number;
  /** Points answered, for a withdrawn row. */
  points?: number;
  /** Points on the same row that refused the answer, for a withdrawn row. */
  pointsRefused?: number;
}

/** The report of one batch answer (#852). */
export interface ReviewAnswerResult {
  answer: ReviewAnswer;
  answered: {
    kind: QueueKind;
    id: number;
    name: string;
    answer: ReviewAnswer;
    did: ReviewAnswerDid;
  }[];
  /** The rows the server would not answer, each with its reason. The batch goes on without them. */
  refused: {
    kind: QueueKind;
    id: number;
    name: string;
    error: string;
  }[];
  /** Rows outside the curator's scope, counted rather than named. */
  outOfScope: number;
  /** The objects whose answer landed and whose re-placement did not. */
  placementFailed: {
    id: number;
    name: string;
    worldViews: PlacementFailure[];
  }[];
}

/** A page of the curator's review queue (ADR-0051). */
export interface ReviewQueue {
  missing: ReviewQueueItem[];
  /** Rows a rule turned down and nobody has answered yet. */
  refused: ReviewQueueItem[];
  /** Refusals a curator confirmed, carried because no other surface shows them. */
  keptOut: ReviewQueueItem[];
  conflicts: ReviewQueueItem[];
  arrivals: ReviewQueueItem[];
  held: ReviewQueueItem[];
  contents: ReviewQueueItem[];
  withdrawn: ReviewQueueItem[];
  answeredWithdrawals: ReviewQueueItem[];
  refusedParts: ReviewQueueItem[];
  limit: number;
  /** The page, in the one order across all seven kinds. The arrays above are a lookup by id. */
  order: QueueOrderEntry[];
  total: number;
  facets: QueueFacets;
  /**
   * The one cursor the seven open kinds share, beside the three offsets the answered lists page by.
   */
  paging: {
    cursor: string | null;
    nextCursor: string | null;
    keptOut: {
      offset: number;
      hasMore: boolean;
    };
    answeredWithdrawals: {
      offset: number;
      hasMore: boolean;
    };
    refusedParts: {
      offset: number;
      hasMore: boolean;
    };
  };
}

/** An object waiting on a curator, or one a curator can take a verdict back from. */
export interface ReviewQueueItem {
  id: number;
  external_id: string;
  name: string;
  kind_id: number;
  kind_name: string;
  missing_since: string | null;
  source_membership: "present" | "former";
  existence: "extant" | "lost";
  kind: "missing" | "conflict" | "refused" | "kept-out" | "arrival" | "held" | "contents" | "withdrawn" | "withdrawn-answered" | "contents-refused";
  image_url?: string | null;
  image_credit?: ImageCredit | null;
  latitude?: number | null;
  longitude?: number | null;
  website_url?: string | null;
  wikipedia_url?: string | null;
  region_names?: string[] | null;
  /** The run's own question about a row it could not settle by its rule (ADR-0058). */
  admission_note?: string | null;
  in_danger?: boolean;
  /** The year the site was listed in danger. */
  danger_since?: number | null;
  /** Why this kind turned the row down, in the rule's own words. */
  admission_reason?: string | null;
  /** When a curator answered. Kept-out items only. */
  state_decided_at?: string | null;
  state_note?: string | null;
  /** The fields a run proposed. Null on every kind that carries no proposal, never absent. */
  proposed: ProposedField[] | null;
  /** When the run whose proposal this is finished. Conflicts only. */
  run_completed_at?: string | null;
  /**
   * The held fields of the object's parts. `held` items only, beside `proposed`, which is the
   * object's own.
   */
  proposed_parts?: HeldPart[] | null;
  /** The famous works the kind's rule weighed, most widely known first, capped at twelve. */
  counted_works?: CountedWork[] | null;
  /** How many works the object holds. */
  counted_works_total?: number | null;
  /**
   * The run this card is about. For an `arrival` it is the run that first saw the row and not a
   * pointer to anything held, and null for a row with no first run recorded.
   */
  sync_log_id?: number | null;
  pending_locations?: number;
  pending_treasures?: number;
  pending_points?: PendingPoint[];
  pending_works?: PendingWork[];
  /** Whether anyone has passed the row. `arrival` items only. */
  curation_state?: string;
  /** How many points the object still offers. */
  offered_locations?: number;
  withdrawn_points?: WithdrawnPoint[] | null;
  answered_points?: AnsweredPoint[] | null;
  answered_points_total?: number;
  refused_points?: RefusedPoint[] | null;
  refused_points_total?: number;
  refused_works?: RefusedWork[] | null;
  refused_works_total?: number;
  /** Whether the take-back would be accepted at all. `contents-refused` items only. */
  takeable?: boolean;
  object_admission?: string | null;
  object_curation_state?: string | null;
}

/** A run's batch set aside for this curator, or brought back (ADR-0051 decision 4). */
export interface RunSetAside {
  syncLogId: number;
  /** The state the caller asked for, whether or not a row changed. */
  setAside: boolean;
}

/** One find dug up at a site (#894). */
export interface SiteFind {
  id: number;
  external_id: string;
  name: string;
  treasure_type: string;
  year: number | null;
  image_url: string | null;
  image_credit: ImageCredit | null;
  is_iconic: boolean;
  sitelinks_count: number;
  /** One entry per building, never empty: a find nobody can go and see is not listed. */
  shown_at: LinkedPlace[];
}

/** The finds dug up at a site, and where they are shown. */
export interface SiteFindsResponse {
  experienceId: number;
  finds: SiteFind[];
  total: number;
}

/** A work marked seen. */
export interface TreasureViewMarked {
  success: true;
  treasureId: number;
  treasureName: string;
  /** The museum marked visited with it, where the call named one. */
  experienceId: number | null;
  experienceName: string | null;
}

/** A work no longer marked seen. */
export interface TreasureViewUnmarked {
  success: true;
  treasureId: number;
}

/** What asking again about turned-down points and works did. */
export interface UnrefuseContentsResult {
  /** Set when the publication landed and re-placing the object into its regions did not. */
  placementFailed?: true;
  /**
   * Where the regions are stale now. Present exactly when `placementFailed` is, and never empty.
   */
  placementFailedWorldViews?: PlacementFailure[];
  experienceId: number;
  locationsRestored: number;
  treasureLinksRestored: number;
  /** Exactly which points came back. */
  locationIds: number[];
  /** Exactly which works came back, by treasure id. */
  treasureIds: number[];
}

/** The works the reader has marked seen. */
export interface ViewedTreasureIds {
  viewedTreasureIds: number[];
}

/** The objects the reader has marked visited. */
export interface VisitedExperienceIds {
  visitedIds: number[];
  total: number;
}

/** The places the reader has marked visited. */
export interface VisitedLocationIds {
  visitedLocationIds: number[];
  /** The same places, keyed by the object id. */
  byExperience: Record<string, number[]>;
  total: number;
}

/** A region the reader has marked visited. */
export interface VisitedRegion {
  region_id: number;
  visited_at: string | null;
  notes: string | null;
}

/** The reader's visited regions, newest first. */
export type VisitedRegions = VisitedRegion[];

/** How far through an object's places the reader is. */
export type VisitedStatus = "not_visited" | "partial" | "visited";

/** A gated sub-kind a `waiting` question groups (ADR-0025). */
export type WaitingSub = "arrival" | "held" | "contents";

/** A point the object lost, waiting on its own verdict. */
export interface WithdrawnPoint {
  id: number;
  name: string | null;
  externalRef: string | null;
  missingSince: string;
  latitude: number | null;
  longitude: number | null;
  /** Whether anyone had been there. The visit survives either answer (ADR-0022). */
  visited: boolean;
  /**
   * How far away the source now offers this same part, in metres, rounded to two decimals. Null
   * where it offers it nowhere.
   */
  replacedMetres: number | null;
  curatedFields?: string[];
}

/** What a curator's correction to a work did. */
export interface WorkEditResult {
  success: true;
  treasureId: number;
  /** The columns this edit took ownership of, which a later run no longer touches. */
  claimed: ("name" | "artists" | "year" | "image_url")[];
  /**
   * Who is named under the new picture. Present only where the picture changed, and null where
   * Commons named nobody in time.
   */
  imageCredit?: ImageCredit | null;
}

/** The map's points, one array per field, all of them the same length. */
export interface WorldPointsResponse {
  detail: PointsDetail;
  /** Echoed rather than assumed, so a layer cannot draw one fold with the other's data. */
  folded: boolean;
  count: number;
  /**
   * Present only when the read hit its cap. A density picture built from a subset is wrong rather
   * than incomplete, so this is never silent.
   */
  truncated?: true;
  lng: number[];
  lat: number[];
  /** Markers only: the pin's identity, for hover and for opening a card. */
  locationId?: number[];
  experienceId?: number[];
  name?: (string | null)[];
  experienceName?: string[];
  /** Markers only: what the pin is coloured by (`kindColors.ts` owns the palette). */
  kindId?: (number | null)[];
  type?: (string | null)[];
  /** Folded only: how many places the pin stands for, which is the badge's number. */
  locationCount?: number[];
}
