/**
 * GENERATED by backend/src/api/generateApiTypes.ts from the response schemas in
 * backend/src/api/responses/ (ADR-0066). Do not edit: run
 * `npm --prefix backend run api:types` after changing a schema. A backend spec
 * fails while this file is not what the schemas render to.
 *
 * Each type is the wire shape of a success body, meaning what `JSON.parse`
 * yields on the client. A timestamp is an ISO string, and an absent optional
 * key is absent. The backend holds every body to its schema before sending it
 * outside production, so these types describe what arrives rather than what
 * one would like.
 */

/** What answering a refusal did. */
export interface AdmissionResult {
  experienceId: number;
  /** The object's own state after the call, unchanged when `published` is false. */
  curationState: MembershipCurationState;
  /** Always empty: an override never applies a held field. */
  appliedFields: string[];
  /** Always empty, for the same reason. */
  claimedFieldsSkipped: string[];
  /** Always empty: a held field of a part is a proposal too, and an override answers none. */
  appliedParts: AppliedPart[];
  /** Always null, for the same reason. */
  fromSyncLogId: null;
  /**
   * Always zero: an override answers no held row, so it leaves none open either. A row holding a
   * proposal keeps its pointer and its own card through an override.
   */
  heldLeftOpen: 0;
  /** Points shown to readers now. */
  locationsPublished: number;
  /** Links to the object's works shown to readers now. */
  treasureLinksPublished: number;
  /** Works shown to readers now. */
  treasuresPublished: number;
  /** Points the source had replaced, no longer shown now that their replacement is. */
  withdrawalsReleased: number;
  /** Set when the publication landed and re-placing the object into its regions did not. */
  placementFailed?: true;
  /**
   * Where the regions are stale now. Present exactly when `placementFailed` is, and never empty.
   */
  placementFailedWorldViews?: PlacementFailure[];
  /** The verdict now standing: `admitted` after an override, `refused` after a confirm. */
  admission: "admitted" | "refused";
  /**
   * Whether this override also made the object visible. True only where the object was unread and
   * the verdict was `override`: putting a gated arrival back is what publishes it (ADR-0025), while
   * overriding the refusal of a visible object says nothing about whether anyone has read it.
   */
  published: boolean;
}

/** One part publishing wrote to, such as a place renamed or a work re-attributed (ADR-0037). */
export interface AppliedPart {
  kind: ContentKind;
  /** The part as the record names it, which is what the curator saw on the card. */
  name: string;
  /** The held fields written to the part now. */
  fields: string[];
  /** Held fields left as the curator wrote them, because the part's own claims hold them. */
  claimedFieldsSkipped: string[];
}

/**
 * Which of an object's contents a part is: one of its points (`locations`) or one of its works
 * (`treasures`).
 */
export type ContentKind = "locations" | "treasures";

/**
 * Where the object stands at the curation gate of its kind. `pending` is shown to nobody but a
 * curator. `auto` and `verified` are shown to readers, `verified` because a person passed it.
 */
export type MembershipCurationState = "pending" | "auto" | "verified";

/**
 * A part the held proposal names that publishing could not write to. Nothing readers see changed.
 */
export interface PartNotFound {
  kind: ContentKind;
  /** The part as the record names it. */
  name: string;
  /**
   * `withdrawn`: no offered row answers to the part any more. `ambiguous`: more than one does, and
   * nothing tells them apart, such as a component listed once per country under one reference.
   */
  reason: "withdrawn" | "ambiguous";
}

/** A world view whose regions the publication could not recompute. */
export interface PlacementFailure {
  /**
   * The world view, or null where listing the world views is what failed, so none was attempted.
   */
  id: number | null;
  name: string | null;
}

/** What a publication did, so the page can say it before the refetch. */
export interface PublishResult {
  experienceId: number;
  /** The object's own state after the call. A contents publish leaves it as it was. */
  curationState: MembershipCurationState;
  /** Held fields written now. */
  appliedFields: string[];
  /** Held fields left as the curator wrote them, because the curator claims them. */
  claimedFieldsSkipped: string[];
  /**
   * The parts whose held fields were written now. Empty on a contents publish, which leaves the
   * proposal where it was.
   */
  appliedParts: AppliedPart[];
  /** Parts the proposal names that nothing could be written to. Present only when there is one. */
  partsNotFound?: PartNotFound[];
  /** The run whose held proposal was applied, or null when none was held. */
  fromSyncLogId: number | null;
  /**
   * Held rows this call left open, at both levels. Non-zero exactly when the card is still
   * standing, because the pointer that keys it was kept. Zero on every call that names no
   * selection.
   */
  heldLeftOpen: number;
  /** Points shown to readers now. */
  locationsPublished: number;
  /** Links to the object's works shown to readers now. */
  treasureLinksPublished: number;
  /** Works shown to readers now. */
  treasuresPublished: number;
  /** Points the source had replaced, no longer shown now that their replacement is. */
  withdrawalsReleased: number;
  /** Set when the publication landed and re-placing the object into its regions did not. */
  placementFailed?: true;
  /**
   * Where the regions are stale now. Present exactly when `placementFailed` is, and never empty.
   */
  placementFailedWorldViews?: PlacementFailure[];
}
