/**
 * GENERATED by backend/src/api/generateApiTypes.ts from the response schemas in
 * backend/src/api/responses/ (ADR-0066). Do not edit: run
 * `npm --prefix backend run api:types` after changing a schema. A backend spec
 * fails while this file is not what the schemas render to.
 *
 * Each type is the wire shape of a success body, meaning what `JSON.parse`
 * yields on the client. A timestamp is an ISO string, and an absent optional
 * key is absent. The backend holds every body to its schema before sending it
 * outside production, so these types describe what arrives rather than what
 * one would like.
 */

/** What taking the source's value for claimed fields did. */
export interface AcceptSourceResult {
  /** Set when the publication landed and re-placing the object into its regions did not. */
  placementFailed?: true;
  /**
   * Where the regions are stale now. Present exactly when `placementFailed` is, and never empty.
   */
  placementFailedWorldViews?: PlacementFailure[];
  experienceId: number;
  /** The fields now holding the source's value. */
  applied: string[];
  /** The claims given up to take it. */
  released: string[];
  /**
   * The points whose own claim on the coordinate went with the object's, because the object's
   * coordinate and its one visible point's are the same fact.
   */
  releasedPoints: number[];
  /** Those of them also put back on the coordinate the run offered. */
  movedPoints: number[];
  /**
   * Whether taking the source's picture also dropped the credit the curator's own edit wrote for
   * it.
   */
  releasedCredit: boolean;
  /** The run whose proposal was taken. */
  fromSyncLogId: number;
}

/** What answering a refusal did. */
export interface AdmissionResult {
  experienceId: number;
  /** The object's own state after the call, unchanged when `published` is false. */
  curationState: MembershipCurationState;
  /** Always empty: an override never applies a held field. */
  appliedFields: string[];
  /** Always empty, for the same reason. */
  claimedFieldsSkipped: string[];
  /** Always empty: a held field of a part is a proposal too, and an override answers none. */
  appliedParts: AppliedPart[];
  /** Always null, for the same reason. */
  fromSyncLogId: null;
  /**
   * Always zero: an override answers no held row, so it leaves none open either. A row holding a
   * proposal keeps its pointer and its own card through an override.
   */
  heldLeftOpen: 0;
  /** Points shown to readers now. */
  locationsPublished: number;
  /** Links to the object's works shown to readers now. */
  treasureLinksPublished: number;
  /** Works shown to readers now. */
  treasuresPublished: number;
  /** Points the source had replaced, no longer shown now that their replacement is. */
  withdrawalsReleased: number;
  /** Set when the publication landed and re-placing the object into its regions did not. */
  placementFailed?: true;
  /**
   * Where the regions are stale now. Present exactly when `placementFailed` is, and never empty.
   */
  placementFailedWorldViews?: PlacementFailure[];
  /** The verdict now standing: `admitted` after an override, `refused` after a confirm. */
  admission: "admitted" | "refused";
  /**
   * Whether this override also made the object visible. True only where the object was unread and
   * the verdict was `override`: putting a gated arrival back is what publishes it (ADR-0025), while
   * overriding the refusal of a visible object says nothing about whether anyone has read it.
   */
  published: boolean;
}

/** One part publishing wrote to, such as a place renamed or a work re-attributed (ADR-0037). */
export interface AppliedPart {
  kind: ContentKind;
  /** The part as the record names it, which is what the curator saw on the card. */
  name: string;
  /** The held fields written to the part now. */
  fields: string[];
  /** Held fields left as the curator wrote them, because the part's own claims hold them. */
  claimedFieldsSkipped: string[];
}

/**
 * Which of an object's contents a part is: one of its points (`locations`) or one of its works
 * (`treasures`).
 */
export type ContentKind = "locations" | "treasures";

/** The newest fifty acts on the object that the curator may see, newest first. */
export type CurationLog = CurationLogEntry[];

/** One act of the object's curation log. */
export interface CurationLogEntry {
  id: number;
  action: "created" | "rejected" | "unrejected" | "edited" | "added_to_region" | "removed_from_region" | "marked_former" | "marked_lost" | "state_restored" | "accepted_source" | "declined_source" | "declined_held" | "missing_dismissed" | "admission_confirmed" | "admission_overridden" | "published" | "location_marked_former" | "location_marked_lost" | "location_state_restored" | "location_missing_dismissed" | "location_edited" | "work_edited" | "arrival_refused" | "contents_refused" | "contents_unrefused";
  region_id: number | null;
  region_name: string | null;
  /** What the act changed, in the shape its action writes. */
  details: Record<string, unknown> | null;
  created_at: string | null;
  /** The curator as they chose to be named, null where they chose nothing. */
  curator_name: string | null;
}

/** One part a refusal of held rows reached. */
export interface DeclinedPart {
  kind: ContentKind;
  /** The part as the record names it. */
  name: string;
  fields: string[];
}

/** What refusing held rows of a gated proposal settled. */
export interface DeclineHeldResult {
  experienceId: number;
  /** The object's own fields refused now. */
  declinedFields: string[];
  /** The parts refused now, grouped as the card grouped them. */
  declinedParts: DeclinedPart[];
  fromSyncLogId: number;
  /** Held rows still open. Zero means the card is gone and the pointer with it. */
  heldLeftOpen: number;
}

/** What standing by the curator's own value did. */
export interface DeclineSourceResult {
  experienceId: number;
  /** The fields whose proposal was turned down, the curator's value kept. */
  declined: string[];
  fromSyncLogId: number;
}

/** What a curator's edit of an object's fields did. */
export interface ExperienceEditResult {
  success: true;
  experienceId: number;
  /** Every field the curator now claims on the object, this edit's included. */
  curatedFields: string[];
}

/** One point of an object. */
export interface ExperienceLocation {
  id: number;
  experience_id: number;
  /** The component the source names, such as one fort of a serial nomination. */
  name: string | null;
  /** The source's own reference, such as `1739-005` for UNESCO. */
  external_ref: string | null;
  /**
   * The point's place in the source's list. Null for a point waiting on its replacement to be
   * published, and sorted last. Read it through `locationLabel` rather than doing arithmetic on it.
   */
  ordinal: number | null;
  longitude: number;
  latitude: number;
  created_at: string | null;
  /**
   * The fields a curator has claimed on the point, such as `name` and `location`, so a row can say
   * it is corrected.
   */
  curated_fields: string[];
  /** Whether the point lies in the region the read was asked about. True where none was named. */
  in_region: boolean;
}

/** An object's own points. */
export interface ExperienceLocationsResponse {
  experienceId: number;
  experienceName: string;
  /** In the source's order, with the points that have no place last. */
  locations: ExperienceLocationWithState[];
  totalLocations: number;
  /** The region `in_region` was asked about, or null where none was named. */
  regionId: number | null;
}

/** One point as its object's own read serves it, with where it stands at the gate. */
export interface ExperienceLocationWithState {
  id: number;
  experience_id: number;
  /** The component the source names, such as one fort of a serial nomination. */
  name: string | null;
  /** The source's own reference, such as `1739-005` for UNESCO. */
  external_ref: string | null;
  /**
   * The point's place in the source's list. Null for a point waiting on its replacement to be
   * published, and sorted last. Read it through `locationLabel` rather than doing arithmetic on it.
   */
  ordinal: number | null;
  longitude: number;
  latitude: number;
  created_at: string | null;
  /**
   * The fields a curator has claimed on the point, such as `name` and `location`, so a row can say
   * it is corrected.
   */
  curated_fields: string[];
  /** Whether the point lies in the region the read was asked about. True where none was named. */
  in_region: boolean;
  curation_state: LocationCurationState;
  /**
   * Set where a curator turned this unread point down. The state cannot say so, because a refused
   * point stays `pending`: publishing shows an unread point and refuses a turned-down one.
   */
  refused_at: string | null;
}

/** An object's lifecycle as a curator's verdict left it. */
export interface ExperienceStateResult {
  experienceId: number;
  /** Whether the source still lists it: `former` once it has delisted it. */
  sourceMembership: "present" | "former";
  /** Whether it is still there to visit: `lost` once it is gone. */
  existence: "extant" | "lost";
}

/** Who a picture is credited to, as `ImageCreditLine` draws it (ADR-0043). */
export interface ImageCredit {
  /** The photographer or uploader, as plain text. */
  author: string | null;
  /** The licence in the words its own name uses: "CC BY-SA 3.0", "Public domain". */
  license: string | null;
  licenseUrl: string | null;
  /** The file page or the site's own page for the object: where the full terms are. */
  detailsUrl: string | null;
}

/**
 * Whether readers see the point yet. `pending` is shown to nobody but a curator until it is
 * published. `auto` and `verified` are shown to readers.
 */
export type LocationCurationState = "pending" | "auto" | "verified";

/** What a curator's correction to a place's name or position did. */
export interface LocationEditResult {
  /** Set when the publication landed and re-placing the object into its regions did not. */
  placementFailed?: true;
  /**
   * Where the regions are stale now. Present exactly when `placementFailed` is, and never empty.
   */
  placementFailedWorldViews?: PlacementFailure[];
  success: true;
  locationId: number;
  /**
   * Whether the object's own coordinate moved with the place. True only where the object holds
   * exactly one visible, published place and this is it.
   */
  anchorMoved: boolean;
}

/** A point's lifecycle as a curator's verdict left it. */
export interface LocationStateResult {
  /** Set when the publication landed and re-placing the object into its regions did not. */
  placementFailed?: true;
  /**
   * Where the regions are stale now. Present exactly when `placementFailed` is, and never empty.
   */
  placementFailedWorldViews?: PlacementFailure[];
  locationId: number;
  experienceId: number;
  sourceMembership: "present" | "former";
  existence: "extant" | "lost";
  /**
   * Whether a reader sees the point now. A verdict can move it either way, and both axes decide it,
   * so the answer says it rather than leaving a card to work it out.
   */
  offeredToReaders: boolean;
}

/** The object a curator created by hand. */
export interface ManualExperienceCreated {
  id: number;
  name: string;
  /** The id the manual source gave it. */
  externalId: string;
}

/**
 * Where the object stands at the curation gate of its kind. `pending` is shown to nobody but a
 * curator. `auto` and `verified` are shown to readers, `verified` because a person passed it.
 */
export type MembershipCurationState = "pending" | "auto" | "verified";

/**
 * A part the held proposal names that publishing could not write to. Nothing readers see changed.
 */
export interface PartNotFound {
  kind: ContentKind;
  /** The part as the record names it. */
  name: string;
  /**
   * `withdrawn`: no offered row answers to the part any more. `ambiguous`: more than one does, and
   * nothing tells them apart, such as a component listed once per country under one reference.
   */
  reason: "withdrawn" | "ambiguous";
}

/** A world view whose regions the publication could not recompute. */
export interface PlacementFailure {
  /**
   * The world view, or null where listing the world views is what failed, so none was attempted.
   */
  id: number | null;
  name: string | null;
}

/** What a publication did, so the page can say it before the refetch. */
export interface PublishResult {
  experienceId: number;
  /** The object's own state after the call. A contents publish leaves it as it was. */
  curationState: MembershipCurationState;
  /** Held fields written now. */
  appliedFields: string[];
  /** Held fields left as the curator wrote them, because the curator claims them. */
  claimedFieldsSkipped: string[];
  /**
   * The parts whose held fields were written now. Empty on a contents publish, which leaves the
   * proposal where it was.
   */
  appliedParts: AppliedPart[];
  /** Parts the proposal names that nothing could be written to. Present only when there is one. */
  partsNotFound?: PartNotFound[];
  /** The run whose held proposal was applied, or null when none was held. */
  fromSyncLogId: number | null;
  /**
   * Held rows this call left open, at both levels. Non-zero exactly when the card is still
   * standing, because the pointer that keys it was kept. Zero on every call that names no
   * selection.
   */
  heldLeftOpen: number;
  /** Points shown to readers now. */
  locationsPublished: number;
  /** Links to the object's works shown to readers now. */
  treasureLinksPublished: number;
  /** Works shown to readers now. */
  treasuresPublished: number;
  /** Points the source had replaced, no longer shown now that their replacement is. */
  withdrawalsReleased: number;
  /** Set when the publication landed and re-placing the object into its regions did not. */
  placementFailed?: true;
  /**
   * Where the regions are stale now. Present exactly when `placementFailed` is, and never empty.
   */
  placementFailedWorldViews?: PlacementFailure[];
}

/** A curator's no to an arrival (ADR-0053). */
export interface RefuseArrivalResult {
  experienceId: number;
  admission: "refused";
  /** The reason the kept-out list shows. */
  reason: string;
}

/** What turning down the unread points and works of an object did. */
export interface RefuseContentsResult {
  /** Set when the publication landed and re-placing the object into its regions did not. */
  placementFailed?: true;
  /**
   * Where the regions are stale now. Present exactly when `placementFailed` is, and never empty.
   */
  placementFailedWorldViews?: PlacementFailure[];
  experienceId: number;
  locationsRefused: number;
  treasureLinksRefused: number;
  /**
   * Old pins a refused arrival had been holding on the map, now withdrawn and asking their own
   * question.
   */
  withdrawalsReleased: number;
}

/** One point as the map and the region list read it. */
export interface RegionExperienceLocation {
  id: number;
  experience_id: number;
  /** The component the source names, such as one fort of a serial nomination. */
  name: string | null;
  /** The source's own reference, such as `1739-005` for UNESCO. */
  external_ref: string | null;
  /**
   * The point's place in the source's list. Null for a point waiting on its replacement to be
   * published, and sorted last. Read it through `locationLabel` rather than doing arithmetic on it.
   */
  ordinal: number | null;
  longitude: number;
  latitude: number;
  created_at: string | null;
  /**
   * The fields a curator has claimed on the point, such as `name` and `location`, so a row can say
   * it is corrected.
   */
  curated_fields: string[];
  /** Whether the point lies in the region the read was asked about. True where none was named. */
  in_region: boolean;
  /**
   * The leaf region the point lies in, with its ancestors, such as `Europe > France > Paris`. It is
   * shown for a point outside the region on screen. Null where the point lies in no region of that
   * world view.
   */
  region_path: string | null;
}

/** The points of a region's objects, in one read rather than one per object. */
export interface RegionExperienceLocationsResponse {
  /** Every point of every object the region list shows, keyed by the object id. */
  locationsByExperience: Record<string, RegionExperienceLocation[]>;
}

/**
 * What rejecting, unrejecting, assigning, unassigning or removing an object in a region did: it is
 * done.
 */
export interface RegionMembershipResult {
  success: true;
  experienceId: number;
  regionId: number;
}

/** What asking again about turned-down points and works did. */
export interface UnrefuseContentsResult {
  /** Set when the publication landed and re-placing the object into its regions did not. */
  placementFailed?: true;
  /**
   * Where the regions are stale now. Present exactly when `placementFailed` is, and never empty.
   */
  placementFailedWorldViews?: PlacementFailure[];
  experienceId: number;
  locationsRestored: number;
  treasureLinksRestored: number;
  /** Exactly which points came back. */
  locationIds: number[];
  /** Exactly which works came back, by treasure id. */
  treasureIds: number[];
}

/** What a curator's correction to a work did. */
export interface WorkEditResult {
  success: true;
  treasureId: number;
  /** The columns this edit took ownership of, which a later run no longer touches. */
  claimed: ("name" | "artists" | "year" | "image_url")[];
  /**
   * Who is named under the new picture. Present only where the picture changed, and null where
   * Commons named nobody in time.
   */
  imageCredit?: ImageCredit | null;
}
