/**
 * In-memory bridge between frontend review responses and a paused Python
 * pipeline worker.
 *
 * The Python CV service can emit interactive-review requests (e.g. water
 * review) that pause the worker thread in the FastAPI process. The backend
 * forwards these requests to the frontend as SSE events. When the operator
 * responds via POST /api/admin/wv-import/water-review/:reviewId, the handler
 * resolves the matching promise here and the pipeline controller forwards
 * the decision to Python via /pipeline/respond/:reviewId.
 *
 * Review IDs are generated by Python with the prefix "py-<kind>-<hex>" so
 * the frontend's POST handler can distinguish Python reviews from JS
 * in-process reviews (which use the existing registerWaterReview / resolveWaterReview
 * pair in wvImportMatchReview.ts).
 */

type Resolver = (decision: unknown) => void;

interface PendingReview {
  resolver: Resolver;
  timeout: ReturnType<typeof setTimeout>;
}

const pending = new Map<string, PendingReview>();

/** Check whether `reviewId` is a Python-originated review. */
export function isPythonReviewId(reviewId: string): boolean {
  return reviewId.startsWith('py-');
}

/** Register a resolver to be called when the operator responds to this Python review. */
export function registerPythonReview(reviewId: string, resolver: Resolver): void {
  // Clear the prior timer for this id so a stale 15-min timer can't delete a
  // freshly registered resolver later.
  const existing = pending.get(reviewId);
  if (existing) clearTimeout(existing.timeout);

  // Auto-expire after 15 minutes so a vanished UI doesn't leak forever.
  const timeout = setTimeout(() => {
    const entry = pending.get(reviewId);
    // Only delete if the entry still matches *this* timer (otherwise a newer
    // registration has replaced us and we must not interfere).
    if (entry && entry.timeout === timeout) {
      pending.delete(reviewId);
      console.warn(`[PythonReview] ${reviewId} expired without a response`);
    }
  }, 15 * 60 * 1000);
  pending.set(reviewId, { resolver, timeout });
}

/**
 * Called by the water-review POST handler when the operator's decision arrives.
 * Returns true if a pending review with this id was found and resolved.
 */
export function resolvePythonReview(reviewId: string, decision: unknown): boolean {
  const entry = pending.get(reviewId);
  if (!entry) return false;
  clearTimeout(entry.timeout);
  pending.delete(reviewId);
  entry.resolver(decision);
  return true;
}
